In [1]:
#Numpy internally works on List and Dictionary and written on C. Hence it is super fast.
#Python is just a wrapper around C
#Numpy is multidimentional

In [3]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])
a.dtype

dtype('int32')

In [10]:
b = np.array([1,2,3,"Anil"])
b

array(['1', '2', '3', 'Anil'], dtype='<U11')

In [6]:
type(a)

numpy.ndarray

In [11]:
l = range(1000)

In [12]:
a = np.arange(1000)

In [13]:
%timeit [i**2 for i in l]   #timeit ia a magic function to Calculate Time difference

361 µs ± 7.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit a**2

2.3 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Creating Numpy Arrays

In [15]:
a = np.array([1,3,4,5,6,"udud"])

In [22]:
a.shape

(6,)

In [23]:
len(a)

6

In [16]:
b =np.array([[1,3,4,5,6,"udud"],[1,2,4,6,7]])

C:\Users\AN2025~1\AppData\Local\Temp/ipykernel_1660/1091926512.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b =np.array([[1,3,4,5,6,"udud"],[1,2,4,6,7]])


In [17]:
b.shape

(2,)

In [48]:
b

array([list([1, 3, 4, 5, 6, 'udud']), list([1, 2, 4, 6, 7])], dtype=object)

In [30]:
b.ndim

1

In [31]:
a[1]

'3'

In [18]:
b

array([list([1, 3, 4, 5, 6, 'udud']), list([1, 2, 4, 6, 7])], dtype=object)

In [19]:
b[1][2]

4

In [32]:
a[2]

'4'

In [35]:
a = np.arange(100)

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
#Mumpy array functions

In [43]:
a = np.ones([3,4])

In [44]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
a = np.random.randint(10,40,size=(5,4))   # Random integer Creation

In [27]:
a

array([[12, 28, 22, 38],
       [21, 30, 14, 23],
       [32, 39, 22, 38],
       [37, 14, 36, 13],
       [35, 39, 26, 14]])

In [62]:
a=np.arange(20)

In [63]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
a[3]

3

In [65]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [73]:
a = [1,2,3,4,5]

In [74]:
b = a  #Call by reference

In [75]:
b

[1, 2, 3, 4, 5]

In [76]:
b[2] = 0

In [77]:
b

[1, 2, 0, 4, 5]

In [78]:
a

[1, 2, 0, 4, 5]

In [79]:
a = [1,2,3,4]

In [80]:
b = a[:]   # Call by Value

In [81]:
b

[1, 2, 3, 4]

In [82]:
b[2] = 0

In [83]:
b

[1, 2, 0, 4]

In [84]:
a

[1, 2, 3, 4]

In [28]:
a = np.random.randint(10,40,size=(5,4))   # Random integer Creation

In [29]:
a

array([[34, 30, 28, 15],
       [35, 11, 14, 24],
       [27, 37, 33, 37],
       [26, 10, 35, 23],
       [28, 26, 39, 29]])

In [31]:
a[2,2] = 0

In [88]:
a[2,1] = 0

In [32]:
a

array([[34, 30, 28, 15],
       [35, 11, 14, 24],
       [27, 37,  0, 37],
       [26, 10, 35, 23],
       [28, 26, 39, 29]])

In [103]:
#Random logic Building Exercise

In [90]:
a = [1,2,3,4,5]
b = [1,0,3,6,7]
a1 = set(a)
b1 = set(b)

In [91]:
a1

{1, 2, 3, 4, 5}

In [92]:
b1

{0, 1, 3, 6, 7}

In [94]:
list(a1.intersection(b1))

[1, 3]

In [95]:
for i in range(len(a)):  #0,1,2,3,4
    if a[i] == b[i]:
        print(a[i])

1
3


In [100]:
a =  [1,2,3,4,5]
b = [1,0,3]

In [102]:
for i in a:
    for j in b:
        if i == j:
            print(i)

1
3


In [104]:
a = np.arange(10)

In [106]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
b = a[:5]

In [110]:
b

array([0, 1, 2, 3, 4])

In [111]:
b[2] = 10

In [112]:
b

array([ 0,  1, 10,  3,  4])

In [113]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [115]:
np.shares_memory(a,b)

True

In [116]:
c = a[:5].copy()

In [117]:
c

array([ 0,  1, 10,  3,  4])

In [118]:
c[2] = 20

In [119]:
c

array([ 0,  1, 20,  3,  4])

In [120]:
a

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [121]:
b

array([ 0,  1, 10,  3,  4])

# Basic Numpy operations

In [122]:
#1. Element Wise operations

In [43]:
a = np.array([1,2,3,4,5])

In [38]:
a

array([1, 2, 3, 4, 5])

In [35]:
l = [1,2,3,4,5]

In [37]:
l * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [42]:
a  = a * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [44]:
import pandas as pd

In [82]:
df = pd.read_csv(r"C:\Anil\Projects\InsuranceFraudDetection-master\code\code\fraudDetection\data\insuranceFraud.csv")

In [87]:
df['age'].describe()

count    1000.000000
mean       38.948000
std         9.140287
min        19.000000
25%        32.000000
50%        38.000000
75%        44.000000
max        64.000000
Name: age, dtype: float64

In [55]:
b = np.array([1,2,3,14,15])

In [56]:
b

array([ 1,  2,  3, 14, 15])

In [57]:
a

array([1, 2, 3, 4, 5])

In [58]:
a - b

array([  0,   0,   0, -10, -10])

In [59]:
a = np.array([1,2,3,4,5])

In [60]:
b = np.array([1,2,3,4,6])

In [63]:
(a==b).any()

True

In [156]:
count = 0
for i in range(len(a)):
    if a[i] == b[i]:
        count += 1
            
if count == len(a):
    print(True)
else:
    print(False)

True


In [64]:
a

array([1, 2, 3, 4, 5])

In [65]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [66]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [67]:
a

array([1, 2, 3, 4, 5])

In [70]:
np.median(a)

3.0

In [161]:
a.max()

5

In [162]:
a.argmin()  # Returns Index

0

In [71]:
a.argmax()

4

In [164]:
a.mean()

3.0

In [166]:
np.median(a)

3.0

In [167]:
a.std()

1.4142135623730951

In [73]:
a = np.random.randint(10,40,size=(3,4))

In [74]:
a

array([[19, 18, 39, 20],
       [10, 10, 34, 16],
       [15, 17, 22, 29]])

In [78]:
a.reshape(1,12)

array([[19, 18, 39, 20, 10, 10, 34, 16, 15, 17, 22, 29]])

In [94]:
c = np.array([[1,2,3],[5,6,7]])

In [96]:
c.ravel()

array([1, 2, 3, 5, 6, 7])

In [97]:
dir(c)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [100]:
a.size

12

In [92]:
a = np.tile(np.arange(0,40,10),(3,1))

In [93]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])